// Case studies — the proof layer. Every entry is a real deliverable that
// already exists in the work section data, recast into a Problem → Pipeline
// → Result shape so the reader sees the mechanics rather than a job title.
//
// All of the original copy is kept: the problem and the detail are the parts
// that make a result believable, so neither is trimmed. What changed is the
// card's internal architecture — the text is split across two columns and
// given distinct jobs instead of stacking as four equal-weight blocks.
//
// No metrics here are invented, and no time period is asserted that the
// source copy did not already claim.
export interface CaseStudy {
	slug: string;
	title: string;
	client: string;
	year: string;
	problem: string;
	/** Exactly three stages: the entry point, the reconciliation, the output. */
	pipeline: readonly [string, string, string];
	result: string;
	detail: string;
	stack: string[];
	link: string;
}

export const caseStudies: CaseStudy[] = [
	{
		slug: "property-ingestion",
		title: "Property ingestion pipeline",
		client: "Iceberg Digital",
		year: "2016",
		problem:
			"Estate agents receive thousands of listings a night from external XML providers — each with its own schema, its own duplicates and its own idea of what a postcode looks like.",
		pipeline: ["XML feeds", "Reconcile", "Live database"],
		result: "0 raw files opened",
		detail:
			"A bespoke CMS ingests every feed on a schedule and reconciles them into one live database. Schema mismatches, duplicate detection and provider outages are all handled in the pipeline, so staff never open a raw file.",
		stack: ["PHP", "MySQL", "XML parsing", "Cron"],
		link: "http://www.nkres.co.uk/",
	},
	{
		slug: "automated-magazines",
		title: "Automated magazine generation",
		client: "Iceberg Digital",
		year: "2016",
		problem:
			"Monthly client magazines were laid out by hand from live property data — a process that took hours per issue and could not keep up with the listings changing daily.",
		pipeline: ["Live listings", "Template", "Print-ready PDF"],
		result: "One click to publish",
		detail:
			"A drag-and-drop interface pulls the client's live properties into InDesign-derived templates. One click produces a print-ready PDF and a digital page-turner. Hundreds of magazines now go out this way.",
		stack: ["PHP", "TCPDF", "HTML templates", "XML"],
		link: "http://www.digitalmag.co.uk/mag/bseenmagazine",
	},
	{
		slug: "valuation-tool",
		title: "Multi-API valuation tool",
		client: "Iceberg Digital",
		year: "2016",
		problem:
			"Getting a valuation meant a phone call: postcode in one system, address in another, price range in a third. Staff relayed the answers by hand.",
		pipeline: ["Postcode", "Address lookup", "Price range"],
		result: "No dashboard switching",
		detail:
			"Two third-party APIs stitched into one flow. A postcode resolves to a full address, that address returns a price range, and the result is displayed live or emailed — no dashboard switching.",
		stack: ["PHP", "REST APIs", "Email"],
		link: "http://outlook.mypropertyprices.com/",
	},
	{
		slug: "email-signatures",
		title: "Dynamic asset linking",
		client: "Iceberg Digital",
		year: "2016",
		problem:
			"Every client's email signature showed their latest magazine cover. When a new issue published, hundreds of signatures had to be regenerated by hand.",
		pipeline: ["Issue published", "Template vars", "Every signature"],
		result: "One publish, every signature",
		detail:
			"Two systems linked so one event triggers the other: publishing a magazine automatically updates the signature imagery across every client account. Manual asset management disappeared.",
		stack: ["PHP", "Template variables", "Automated deploy"],
		link: "/images/morganalexandersig.gif",
	},
];
